### ISSUE TITLE
[Report] msxml6 link broken

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/dependencies#1]
**Which dependency?**
msxml6

**Problem type**
- download failed/broken url

**Comment by francescomasala** [comment]
Microsoft removed the [link](https://www.microsoft.com/en-us/download/details.aspx?id=25) from their website

**Comment by mirkobrombin** [comment]
Perhaps it is present from other sources or the link has changed 🤨

**Comment by francescomasala** [comment]
The problem is that that file is included natively in Windows 10 and is not available from official Microsoft sources as they have removed the links to the various installers containing that DLL

**Comment by mirkobrombin** [comment]
It should be present in some service packs but the cab extraction functionality will not be supported before v4

**Comment by mirkobrombin** [comment]
Ref: https://github.com/bottlesdevs/libbottles/issues/1

**Comment by mirkobrombin** [comment]
Already available https://github.com/bottlesdevs/dependencies/blob/main/Essentials/msxml6.yml
