### ISSUE TITLE
[Request dependency] Microsoft .NET Framework 2.0 Service Pack 1 (x64) 

### ISSUE THREAD

**Issue by ormayraz** [bottlesdevs/dependencies#10]
**Dependency name**: Microsoft .NET Framework 2.0 Service Pack 1 (x64) 

**Official link to the download page (not direct download)** https://www.microsoft.com/en-us/download/details.aspx?id=6041

**Is this dependency compatible with Wine?**
- [ ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [x] I have not tested

**Useful links**
They can be links to guides for its implementation or testing or other. Each reference can be useful to maintainers to implement the dependency.

**Comment by bayazidbh** [comment]
At this point, would it be worth it to just make a batch install "dotnet_all" dependency to automate the installation process?

**Comment by mirkobrombin** [comment]
> At this point, would it be worth it to just make a batch install "dotnet_all" dependency to automate the installation process?

I think installing all net framework will broke a lot of apps, btw that script will spawn every installer as the quiet flag is broken in some cases (investigating)

**Comment by AvantGov** [comment]
While we are discussing older MS .NET packs, I am attempting to install a software that is requiring 
- .NET Framework 2.0 Service Pack 2 (https://www.microsoft.com/en-us/download/details.aspx?id=9834)
- .NET Framework 3.0 (http://www.oldversion.com/windows/net-framework-3-0 maybe?)
- .NET Framework 3.0 Service Pack 2 (https://www.microsoft.com/en-us/download/details.aspx?id=29795)
- .NET Framework 4.8 (x86 and x64) (https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48 maybe?)

I believe the 4.8 is a matter of having the 4.8 (x64) version, but not having the x86, which (admittedly) I am not at all familiar with. Is this the case? 

While I am in part commenting on this issue to put the thought of adding these dependencies to the repo, I am also wondering if there is any cross over among these packages or a work around to run the software without having them explicitly? (ie: wouldn't 3.0 contain everything that 2.0 contains and more?)

**Comment by mirkobrombin** [comment]
What software is it?

**Comment by AvantGov** [comment]
Q-SYS Designer, used for programming automation systems and interfaces for enterprise conference centers, etc. 
https://www.qsc.com/resources/software-and-firmware/q-sys-designer/ 

Thanks for being so responsive on this!

**Comment by mirkobrombin** [comment]
It should just works now, there was an error which was fixed in 2022.1.28

**Comment by zouyonghao** [comment]
> Locked by:
> 
> * missing dotnet20 dependency
> * dotnet20 Microsoft direct URL is unreachable (not a really a blocking thing)
> * win2000 support in Bottles (win2008/win2003 seems working so maybe this is not needed https://bugs.winehq.org/show_bug.cgi?id=10467#c57)
> 
> Current `dotnet20` manifest state:
> 
> ```yaml
> Name: dotnet20
> Description: Microsoft .NET Framework 2.0
> Provider: Microsoft
> License: Microsoft EULA
> License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
> Dependencies: []
> Steps:
> - action: uninstall
>   file_name: Wine Mono
> 
> - action: set_windows
>   version: win2003
> 
> - action: install_exe
>   file_name: dotnetfx.exe
>   url: https://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe
>   arguments: /q /c:"install.exe /q" # will silently fails on win64
>   rename: dotnet20x32.exe
>   file_checksum: 93a13358898a54643adbca67d1533462
> 
> - action: install_exe
>   file_name: NetFx64.exe
>   url: https://download.microsoft.com/download/a/3/f/a3f1bf98-18f3-4036-9b68-8e6de530ce0a/NetFx64.exe
>   arguments: /q /c:"install.exe /q" # will silently fails on win32
>   rename: dotnet20x64.exe
>   file_checksum: 93a13358898a54643adbca67d1533462
> 
> - action: set_windows
>   version: win10
> 
> - action: override_dll
>   dll: mscorwks
>   type: native,builtin
> ```

Can we add this in a recent release?

**Comment by mirkobrombin** [comment]
> > Locked by:
> > 
> > * missing dotnet20 dependency
> > * dotnet20 Microsoft direct URL is unreachable (not a really a blocking thing)
> > * win2000 support in Bottles (win2008/win2003 seems working so maybe this is not needed https://bugs.winehq.org/show_bug.cgi?id=10467#c57)
> > 
> > Current `dotnet20` manifest state:
> > ```yaml
> > Name: dotnet20
> > Description: Microsoft .NET Framework 2.0
> > Provider: Microsoft
> > License: Microsoft EULA
> > License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
> > Dependencies: []
> > Steps:
> > - action: uninstall
> >   file_name: Wine Mono
> > 
> > - action: set_windows
> >   version: win2003
> > 
> > - action: install_exe
> >   file_name: dotnetfx.exe
> >   url: https://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe
> >   arguments: /q /c:"install.exe /q" # will silently fails on win64
> >   rename: dotnet20x32.exe
> >   file_checksum: 93a13358898a54643adbca67d1533462
> > 
> > - action: install_exe
> >   file_name: NetFx64.exe
> >   url: https://download.microsoft.com/download/a/3/f/a3f1bf98-18f3-4036-9b68-8e6de530ce0a/NetFx64.exe
> >   arguments: /q /c:"install.exe /q" # will silently fails on win32
> >   rename: dotnet20x64.exe
> >   file_checksum: 93a13358898a54643adbca67d1533462
> > 
> > - action: set_windows
> >   version: win10
> > 
> > - action: override_dll
> >   dll: mscorwks
> >   type: native,builtin
> > ```
> 
> Can we add this in a recent release?

Download for 64bit is broken: https://download.microsoft.com/download/a/3/f/a3f1bf98-18f3-4036-9b68-8e6de530ce0a/NetFx64.exe

So we can provide this only on 32bit bottles.
