### ISSUE TITLE
[Request dependency] FNA

### ISSUE THREAD

**Issue by Foro38** [bottlesdevs/dependencies#108]
**Dependency name**: FNA

**Official link to the download page (not direct download)** https://fna-xna.github.io/

**Is this dependency compatible with Wine?**
- [ ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [X] I have not tested

**Useful links**
https://github.com/FNA-XNA/FNA/wiki

**Comment by jannuary** [comment]
From what I understand, it's not a dependency per se, but something that requires developer's effort to use, hence closing.
