### ISSUE TITLE
[Request dependency] l3codecx, winxp, directshow

### ISSUE THREAD

**Issue by nclm** [bottlesdevs/dependencies#110]
I want to play the game “Her Story” but the videos in the game are not playing.
I found this page that notes that for playing the game in Wine, this should be installed:

`winetricks ffdshow l3codecx winxp directshow`

I found ffdshow in Bottles but not the others. The videos are not playing when only installing ffdshow.

**Dependency name**: 
- l3codecx
- winxp
- directshow

**Official link to the download page (not direct download)** ?

**Is this dependency compatible with Wine?**
- [ ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [x] I have not tested

**Useful links**
?

**Comment by mirkobrombin** [comment]
winxp is not a dependency, just choose windows xp in the Windows version menu
