### ISSUE TITLE
[Report] The vbrun6 dependency url broke

### ISSUE THREAD

**Issue by MrPancakes39** [bottlesdevs/dependencies#113]
**Which dependency?**
 - vbrun6

**Problem type**
- download failed/broken url

**Describe the problem**
Tried to install vbrun6 as dependency, it failed with a 404 error

**Log**
```
19:14:16 (INFO) Installing dependency [vbrun6] in bottle [UNI_APPS]. 
19:14:16 (WARNING) Failed to download [https://lon-01.lo4d.com/files/visual-basic-runtime-files/VB6.0-KB290887-X86.exe] with code: 404 != 200 
```

**Comment by keenanweaver** [comment]
This issue can be closed https://github.com/bottlesdevs/dependencies/pull/117

**Comment by MrPancakes39** [comment]
Great Thanks! ❤️
