### ISSUE TITLE
[BUG] msxml 4 could not be installed

### ISSUE THREAD

**Issue by unrealsolver** [bottlesdevs/dependencies#121]
Why installing Fusion360
```
20:51:35 (INFO) Installing dependency [msxml4] in bottle [Fusion].
20:51:36 (ERROR) Failed to download [https://web.archive.org/web/20210506101448/http://download.microsoft.com/download/A/2/D/A2D8587D-0027-4217-9DAD-38AFDB0A177E/msxml.msi]
```
Apparently, file was moved elsewhere

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/183995443-f92e70fd-9768-4b90-9803-4f4b5b92bba4.png)
I think this was a temporary issue.

**Comment by unrealsolver** [comment]
Apparently, this was Uzbekistan issue... :facepalm: Local ISP blocks waybackmachine which is used for storing msxml msi files.
