### ISSUE TITLE
[Request dependency] gmdls

### ISSUE THREAD

**Issue by alesej** [bottlesdevs/dependencies#122]
**Dependency name**: gmdls

**Official link to the download page (not direct download)** winetricks gmdls is the equivalent, can’t find a download page for it that looks legitimate 

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Comment by keenanweaver** [comment]
Here is what Winetricks is doing: https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L10463

If these steps were to be replicated, it's not currently possible using the Bottles [manifest actions](https://maintainers.usebottles.com/dependencies/structure/Actions). Looks like they're making a directory (no relevant action as far as the documentation states) and also a symlink, which could just use Bottles' `copy_file`.

**Comment by mirkobrombin** [comment]
A solution might be allowing `copy_file` to make the path if not already exists.
Personal ref: https://github.com/bottlesdevs/Bottles/blob/e8018ab6f20b8c3fe9760692c77d6f6a78be0dc2/bottles/backend/managers/dependency.py#L530
