### ISSUE TITLE
[Request dependency] Adobe Reader DC installer needs mspatcha.dll

### ISSUE THREAD

**Issue by silviucc** [bottlesdevs/dependencies#124]
**Dependency name**: mspatcha.dll

**Official link to the download page (not direct download)** https://...
No longer available from Microsoft but can be found in the Windows 2000 SP4 installer via WayBack machine

**Is this dependency compatible with Wine?**
- [x ] Yes

**Useful links**
They can be links to guides for its implementation or testing or other. Each reference can be useful to maintainers to implement the dependency.

https://github.com/Winetricks/winetricks/issues/600

https://github.com/Winetricks/winetricks/blob/master/src/winetricks

```
w_metadata mspatcha dlls \
    title="MS mspatcha" \
    publisher="Microsoft" \
    year="2004" \
    media="download" \
    file1="../win2ksp4/W2KSP4_EN.EXE" \
    installed_exe1="${W_SYSTEM32_DLLS_WIN}/mspatcha.dll"

load_mspatcha()
{
    helper_win2ksp4 i386/mspatcha.dl_
    w_try_cabextract --directory="${W_SYSTEM32_DLLS}" "${W_TMP}"/i386/mspatcha.dl_

    w_override_dlls native,builtin mspatcha
}
```

**Comment by mirkobrombin** [comment]
Thanks for reporting
