### ISSUE TITLE
[Report] dll gdiplus.dll not found in temp, there should be other errors from cabextract.

### ISSUE THREAD

**Issue by qogusdn1017** [bottlesdevs/dependencies#13]
**Which dependency?**
gdiplus

**Problem type**
- download failed/broken url? I don't know why this problem is still happening, after I PR-ed the gdiplus related one.

**Describe the problem**
Download the gdiplus dependency, and you'll find this issue.

---

P.S. Anyway to debug the bottles? This was the only error message that I got for, so I want to know the full progress of downloading, extracting, finding files, etc.

Anyways, thanks for writing this amazing program once again.

**Comment by mirkobrombin** [comment]
Hi, thanks :) You can see what Bottles is doing from download/operation icon that appear in the titlebar when it is performing something. Otherwise you can just start it trough your terminal to see all outputs.

**Comment by qogusdn1017** [comment]
Unfortunately the only clue that I can find on the terminal was this error msg... I'll test again later too!

**Comment by qogusdn1017** [comment]
Simple question, is there are any way to check new dependencies or modified Manifests?

**Comment by mirkobrombin** [comment]
> Simple question, is there are any way to check new dependencies or modified Manifests?
> 
> Because I need to test dotnet461 & other stuff. See: #15

I answered you in the PR

**Comment by Nocifer** [comment]
I think this has now been fixed not only with @qogusdn1017's PR #15 but also with the more recent commit 8a6368e. The `gdiplus` dependency installs fine (I just checked) so this bug can be closed as fixed.

**Comment by mirkobrombin** [comment]
Fine, thanks for checking

**Comment by qogusdn1017** [comment]
👍
