### ISSUE TITLE
[Report] msls31

### ISSUE THREAD

**Issue by ThegodC0der** [bottlesdevs/dependencies#138]
**Which dependency?**
msls31

**Problem type**
download failed

**Describe the problem**
url seems to not be up anymore
https://web.archive.org/web/20160710055851if_/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe

**Comment by francescomasala** [comment]
For me the link is up, to be sure I'll reupload it on our CDN


Il giorno gio 13 ott 2022 alle ore 23:55 ThegodC0der <
***@***.***> ha scritto:

**Comment by francescomasala** [comment]
Sorry, fixed in commit eddd5c8191a80eee6043659d1ba200f50a5c4187
