### ISSUE TITLE
Open my linux browser from A bottle 

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [bottlesdevs/dependencies#151]
My software installed wants to open a new page on my browser but i can't open it.  The browser never open up

![image](https://user-images.githubusercontent.com/45184918/204938989-43800018-5c7f-4cf4-86b5-aff2ab98ae28.png)

**Comment by gnuhead-chieb** [comment]
http://www.webupd8.org/2010/03/how-to-make-wine-open-links-in-your.html
Did you try this?

**Comment by jojojojojoj5564656465465** [comment]
no but it's exactly what i need
