### ISSUE TITLE
[Report] Directshow

### ISSUE THREAD

**Issue by BiosElement** [bottlesdevs/dependencies#152]
**Which dependency?**
directshow

**Problem type**
- Missing from Bottles 2022.11.14 on SteamDeck as well as not listed in the dependency web database.

**Describe the problem**
Dependency DirectShow is missing despite it's apparent addition in #132. It was also reported missing in Issue #67 back in October.

**Comment by Kinsteen** [comment]
It seems like PR https://github.com/bottlesdevs/dependencies/pull/133 removed those dependencies for some reason, it probably was not intended and the commits 4ce78b0e3de0c3ff205376897d520a89cefb539a and 4901d6467cd83ebd7ed6aa9a97316136a7059f6d should be reverted.

**Comment by keenanweaver** [comment]
Definitely not intended! Sorry about that.

**Comment by charstring1** [comment]
Wondering if this is still outstanding? Using Bottles on Steamdeck, not seeing directshow in the dependencies as of the latest 51.0 release.
