### ISSUE TITLE
[Report] faudio installation fails due to incorrect extraction of the .tar.xz archive

### ISSUE THREAD

**Issue by TKasperczyk** [bottlesdevs/dependencies#173]
**Which dependency?**
faudio (20.07)

**Problem type**
Failed to install

**Describe the problem**
The dependency fails to install with the following error:

```
01:14:28 (INFO) Installing dependency [faudio] in bottle [Gaming]. 
faudio-20.07.tar.xz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (13.8 MB/13.8 MB - 9.5 MB)

01:14:30 (INFO) Renaming [faudio-20.07.tar.xz] to [faudio_20_07.xz]. 
patool: Extracting /home/luth/.local/share/bottles/temp/faudio_20_07.xz ...
patool: running '/usr/bin/xz' -c -d -- '/home/luth/.local/share/bottles/temp/faudio_20_07.xz' > '/home/luth/.local/share/bottles/temp/faudio_20_07/faudio_20_07'
patool:     with shell='True'
patool: ... /home/luth/.local/share/bottles/temp/faudio_20_07.xz extracted to `/home/luth/.local/share/bottles/temp/faudio_20_07'.
01:14:31 (INFO) File(s) not found in /home/luth/.local/share/bottles/temp/faudio_20_07/faudio-20.07/x64
```

`/home/luth/.local/share/bottles/temp/faudio_20_07/faudio-20.07` isn't a directory, it's a TAR archive which needs to be extracted first. As you can see, the file that is downloaded has the `.tar.xz` extension, so extracting it with `/usr/bin/xz' -c -d` won't be enough. 
I temporarily fixed the problem by: 
1. `cd /home/luth/.local/share/bottles/temp/faudio_20_07`
2. `tar -xvf faudio_20_07 && mv ./faudio-20.07 ~/`
3. `cd ../` (current dir: `~/.local/share/bottles/temp`)
4. Clicked on the Install button and immediately executed `mv ~/faudio-20.07 ./faudio_20_07/`

The reason it had to be done this way was that the installation script removes the contents of `~/.local/share/bottles/temp/faudio_20_07` as the first step. By moving the extracted faudio installation files to the correct directory after the script's `rm` command, but before it checks for the existence of `~/.local/share/bottles/temp/faudio_20_07/faudio-20.07/x64`, allows us to work around the problem.

**How to fix it**
Remove the "renaming" step (.tar.xz > .xz) from the installation script and change the extraction command to: `tar -xvJf ~/.local/share/bottles/temp/faudio_20_07.tar.xz`

**Comment by SuperSamus** [comment]
I'm wondering if FAudio should be in the list of dependencies at all.
- It's included in Wine since 7.0.
[Source](https://www.winehq.org/announce/7.0):
> - The following libraries are bundled in the source tree and built as PE libraries, so they are no longer required at the Unix level:
>   - Faudio

- [The repository](https://github.com/Kron4ek/FAudio-Builds) where Bottles takes FAudio from has been archived 2 years ago, and says to prefer the native FAudio.
