### ISSUE TITLE
[Request dependency]

### ISSUE THREAD

**Issue by ZHassanQ** [bottlesdevs/dependencies#189]
**Dependency name**: Adobe AIR

**Official link to the download page (not direct download)** http://www.adobe.com/go/getair

**Is this dependency compatible with Wine?**

- [ ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [X] I have not tested

**Useful links**

I don't have any information.

**Comment by orowith2os** [comment]
We can't just add a dependency like this without knowing if it works, why it's needed, and its history. At least try it out and provide more (*useful*) details before requesting it.
