### ISSUE TITLE
[Request dependency] dotnetcoredesktop8

### ISSUE THREAD

**Issue by MadByteDE** [bottlesdevs/dependencies#227]
**Dependency name**: dotnetcoredesktop8

**Official link to the download page (not direct download)** https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

[MS .NET Desktop Runtime 8.0 LTS is already available in latest winetricks](https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L10219)

**Comment by mirkobrombin** [comment]
Feel free to open a PR since nobody did it already

**Comment by DocBrown101** [comment]
@mirkobrombin, do you have time for a review?

**Comment by mirkobrombin** [comment]
I'll review today
