### ISSUE TITLE
[Report] d3d9 and d3dcompiler_xx dependencies fail to install correctly

### ISSUE THREAD

**Issue by Nocifer** [bottlesdevs/dependencies#24]
**Which dependency?**
d3dx9, d3dcompiler_43, d3dcompiler_46, d3dcompiler_47

**Problem type**
- Failed to install correctly (bottle.yml reports everything OK)

**Describe the problem**
I noticed that some D3D9 games that run just fine with Lutris or with the system-wide Wine fail to run with Bottles. The best hint was a game reporting an issue with Direct3D 9 not being correctly installed. I checked, and I found the following:

- In system32, all the dlls are still the original Wine stubs instead of the Microsoft-provided real dlls:

![2022-01-18_17:11:24](https://user-images.githubusercontent.com/6195422/149966548-d5c976b9-9c79-4396-a4bf-da10edb2c815.png)

- In syswow64, the dlls have been installed but there are also some extra files that probably shouldn't be there:

![2022-01-18_17:12:17](https://user-images.githubusercontent.com/6195422/149966723-f8bb100e-b8d1-481a-9296-dc72165d5475.png)

Opening the **w9x** and **x86** .inf files in syswow64, it turns out they're setup instructions for x32 and x64 systems respectively. So either these files being present is standard procedure when installing the d3d9 runtime and I just hadn't realized until now, or this hints at a somehow botched install.

Mass-overwriting with the dlls contained in Lutris's D3D Extras fixed the issue completely, so this is indeed a d3d9 runtime and/or d3dcompiler_xx setup issue. But I had to overwrite over both system32 and syswow64 before my game launched, which means that not even the x32 files had installed correctly (either that, or a separate d3dcompiler_xx.dll was needed for this specific game that isn't provided by Bottles's dependencies but is contained in Lutris's D3D Extras - but this belongs to a separate [Request dependency] report.

**Comment by mirkobrombin** [comment]
Thanks for your report, there was 2 problems:
- the dependency was extracting all files starting with the declared `file_name` (e.g. `d3dx9_40`)  instead of the single DLL (e.g. `d3dx9_40.dll`)
- there was a wrong condition in Bottles that was avoiding the 64bit DLLs from being installed (these are the DLLs placed in `system32` on a `win64` bottle, as Windows use `system32` for 64bit and `syswow64` for 32bit on a 64bit system)

I'm pushing an hotfix, thanks for your report 🙏

**Comment by Nocifer** [comment]
Don't thank me yet because apparently it's still not working correctly :P

Now the junk files in syswow64 are gone, but the x64 dlls still don't get installed:

![2022-01-18_19:16:49](https://user-images.githubusercontent.com/6195422/149986106-61fd6b78-f517-473c-967c-3408d9218682.png)

This screenshot is from just now, i.e. with your latest changes included, and with all four of d3d9 and d3dcompiler_43/46/47 installed.

**Comment by mirkobrombin** [comment]
You need the hotfix which is coming but took ~2/3h

**Comment by Nocifer** [comment]
Alright, tested with the latest hotfix and everything installs correctly except for the x64 dll of d3dcompiler_47. I hope I'm not doing anything wrong:

![2022-01-18_19:36:47](https://user-images.githubusercontent.com/6195422/149989172-f44ec19f-1c41-460e-9575-b4727e1fe272.png)

**Comment by Nocifer** [comment]
Now it's fixed, thanks!

**Comment by mirkobrombin** [comment]
You are welcome ;)
