### ISSUE TITLE
Provide size

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/dependencies#3]
Providing the dependency size, we can show it the user, so he can imagine how it should take to install that dependency.

**Comment by mirkobrombin** [comment]
Freeze by new download manager

**Comment by francescomasala** [comment]
Added size with commit a8cd31ae8db03dde56807fc02025e4b9e580e4cb and updated it with CI 3273117b00baca9e2679fb3f1563742ad6ac84c4
