### ISSUE TITLE
[Request dependency] dotnet462

### ISSUE THREAD

**Issue by pieplu** [bottlesdevs/dependencies#30]
**Dependency name**: Microsoft .NET 4.6.2
Actually 4.6.1 is on your dependencie repo. I hope 4.6.2 can be added.

**Official link to the download page (not direct download)** https://dotnet.microsoft.com/en-us/download/dotnet-framework/net462 or https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net462-offline-installer ?

**Is this dependency compatible with Wine?**
- [X] Yes (https://appdb.winehq.org/objectManager.php?sClass=version&iId=34702)
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

Other thing. You create a doc to add a dependencie on this repo, but I don't find anything to know how to test that on your local installed Bottles application. ( https://github.com/bottlesdevs/dependencies#how-to-contribute )
How do we do to add "custom" dependencies?
Have you some link to help me try that? It will be very helpfull
Thanks :) An thanks for all the time you spend on this project!

**Comment by mirkobrombin** [comment]
Implemented in ee35a9d9c8a6ea60e3a45b39b41ed90593efde92
