### ISSUE TITLE
[Request dependency] Adobe Air

### ISSUE THREAD

**Issue by Midnight1938** [bottlesdevs/dependencies#31]
**Dependency name**: Adobe Air

**Official link to the download page (not direct download)** Depreciated

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
- [Webarchive link to official distribution](https://web.archive.org/web/20201220221650/https://get.adobe.com/air/otherversions/)
- [Official Help Page](https://help.adobe.com/en_US/air/build/WS5b3ccc516d4fbf351e63e3d118666ade46-7fee.html)
- Does have  a linux distribution aswell, maybe that is also helpful?

**Comment by francescomasala** [comment]
Added dep. in commit 02427ee44ead8c3dc601dbf9627bcb7030127d7a
