### ISSUE TITLE
[Request dependency] vcredist2017

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/dependencies#32]
**Dependency name**: Visual C++ 2017 64bit

**Official link to the download page (not direct download)** https://visualstudio.microsoft.com/vs/older-downloads/

**Is this dependency compatible with Wine?**
- [ x ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

There already is vcredist 2015 and vcredist 2019 which says it is 2015-2019. I am trying to install a program that seems to specifically want 2017. If vcredist 2019 should cover both 2015 and 2017 there also shouldn't be a separate one for 2015. Maybe it is the same where some programs need 2015 specifically?

**Comment by mirkobrombin** [comment]
vcredist2019 already cover vcredist2017. I think the vcredist2015 is just a refuse.
