### ISSUE TITLE
[Report] .NET Framework 4.6.1 is not supported on this operating system

### ISSUE THREAD

**Issue by Redop89** [bottlesdevs/dependencies#36]
**Which dependency?**
e.g. dotnet461

**Problem type**

- failed to install (provide your bottle.json)
-------------
Name: dotnet461
Description: Microsoft .NET Framework 4.6.1
Provider: Microsoft
License: Microsoft EULA
License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
Dependencies: []
Steps:
- action: uninstall
  file_name: Wine Mono

- action: set_windows
  version: win7
  
- action: install_exe
  environment: 
    WINEDLLOVERRIDES: fusion=b
  file_name: NDP461-KB3102436-x86-x64-AllOS-ENU.exe
  url: https://download.microsoft.com/download/E/4/1/E4173890-A24A-4936-9FC9-AF930FE3FA40/NDP461-KB3102436-x86-x64-AllOS-ENU.exe
  rename: dotnet461.exe
  file_checksum: 864056903748706e251fec9f5d887ef9
  arguments: /sfxlang:1027 /norestart

- action: set_windows
  version: win10

- action: override_dll
  dll: mscoree
  type: native

---------------

**Describe the problem**
I get an error message when installing this dependency, It says "The .NET Framework 4.6.1 is not supported on this operating system."
I tired both with Windows 10 and Win 8. This is on the latest flatpak release i.e 2022.1.28-trento on Manjaro (Kernel 5.15)

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by mirkobrombin** [comment]
Hotfix coming, will be available soon on flathub and aur.
