### ISSUE TITLE
[Request dependency] Microsoft Visual Basic 6.0 Runtime

### ISSUE THREAD

**Issue by alexmalykh** [bottlesdevs/dependencies#37]
**Dependency name**: Microsoft Visual Basic 6.0 Runtime

**Official link to the download page (not direct download)** probably https://www.microsoft.com/en-us/download/details.aspx?id=7030

**Is this dependency compatible with Wine?**
- [ ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [x] I have not tested, but this runtime can be installed using winetricks

**Comment by mirkobrombin** [comment]
Already present
