### ISSUE TITLE
[Report] New hash for vcredist2019 dependency

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/dependencies#38]
Hi, the new hash is here:

```
(14:51:11) WARNING File [vcredist2019_x64.exe] already exists in temp, skipping. 
(14:51:11) ERROR Downloaded file [VC_redist.x64.exe] looks corrupted. 
(14:51:11) ERROR Source cksum: [35431d059197b67227cd12f841733539] downloaded: [291e0c486cbe22cb000c5e541c9e8317] 
```

**Comment by mirkobrombin** [comment]
Seems like you received a corrupted version of the package, because the hash in the repository is `35431d059197b67227cd12f841733539` which is the same from the source

**Comment by Bananaman** [comment]
@mirkobrombin Nice find, yep you are right. I tried again and it worked. Now I see why Bottles uses hashes to make sure the download was complete. ;)

**Comment by mirkobrombin** [comment]
Ahah nice
