### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by jgrecoarroyo** [bottlesdevs/dependencies#39]
**Which dependency?**
atmlib (Adobe Type Manager)

**Problem type**
- download failed/broken url

**Describe the problem**
When trying to install this dependency, after clicking on the "install" button, it will be loading forever (days). Is there a way to install this dependency manually or using CLI? Thanks!

**Comment by mirkobrombin** [comment]
I'm able to install it from Bottles and took ~3min 

Btw download it following the instructions here: https://github.com/bottlesdevs/dependencies/blob/main/Essentials/atmlib.yml
