### ISSUE TITLE
[Report] dotnet472 installation fails

### ISSUE THREAD

**Issue by nill14** [bottlesdevs/dependencies#47]
Installation of dotnet472 into a newly created application bottle fails. The setup program returns with blocked installation.

Steps to reproduce:
1) create a new application bottle
2) from dependencies tab select dotnet472
3) dotnet installation fails (The installation was blocked)

**Comment by nill14** [comment]
Using version 2022.1.28-trento

**Comment by nill14** [comment]
Using version 2022.1.28-trento

The installation is blocked because it says it is already installed. (It isn't.)

**Comment by francescomasala** [comment]
Hi! I've checked the download link and the checksum and they seem to be correct, so I would ask you to open an issue on [bottlesdesvs/bottles](https://github.com/bottlesdevs/Bottles)
