### ISSUE TITLE
[Request dependency] Media foundation

### ISSUE THREAD

**Issue by Crono23** [bottlesdevs/dependencies#5]
**Dependency name**: Media foundation

**Official link to the download page (not direct download)** https://www.catalog.update.microsoft.com/Search.aspx?q=kb976932

**Is this dependency compatible with Wine?**
Yes

**Useful links**
https://github.com/z0z0z/mf-installcab

**Comment by mirkobrombin** [comment]
DLLs that should be included:
https://github.com/Winetricks/winetricks/issues/1132#issue-379818426

**Comment by mirkobrombin** [comment]
Uploaded
