### ISSUE TITLE
[Report] MFC42.DLL

### ISSUE THREAD

**Issue by dhariady** [bottlesdevs/dependencies#52]
**Which dependency?**
mediafoundation

**Problem type**
MFC42.DLL cannot be found

**Describe the problem**
My app required MFC42.DLL, I installed mediafoundation package as recommended but still it cannot be found.

**Comment by mirkobrombin** [comment]
My bad, such dependency should be provided by vcredist6

**Comment by dhariady** [comment]
ah i see... i think we should close this then. thank you.

**Comment by natrist** [comment]
I also encountered the same issue today. Maybe it would be wise to return vcredist6 when a user searches for things like 'MFC', 'MFC42.dll', 'Microsoft Foundation Class', etc.?
