### ISSUE TITLE
[Request dependency] DirectPlay

### ISSUE THREAD

**Issue by onlybugreports** [bottlesdevs/dependencies#53]
**Dependency name**: dependency name here
DirectPlay

**Official link to the download page (not direct download)** https://...
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Is this dependency compatible with Wine?**
- [X] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
I usually install on regular wine using winetricks: 
winetricks directplay

It has been deprecated on recent windows versions. Maybe it needs to be used in compatibility mode for XP or win7.

I believe it overrides the following dlls:

Executing wine regsvr32 dplayx.dll
regsvr32: Successfully registered DLL 'dplayx.dll'
Executing wine regsvr32 dpnet.dll
regsvr32: Successfully registered DLL 'dpnet.dll'
Executing wine regsvr32 dpnhpast.dll
regsvr32: Successfully registered DLL 'dpnhpast.dll'

**Comment by mirkobrombin** [comment]
Locked by https://github.com/bottlesdevs/Bottles/issues/1485
