### ISSUE TITLE
[Request dependency] mfc40

### ISSUE THREAD

**Issue by Raubsiedler** [bottlesdevs/dependencies#55]
**Dependency name**: mfc40
**Official link to the download page (not direct download)** https://web.archive.org/web/20070316220826/http://activex.microsoft.com/controls/vc/mfc40.cab

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
https://github.com/noahocker/winetricks/issues/487

**Comment by francescomasala** [comment]
I'm downloading this file on our CDN, so wait 10 minutes and i'll upload the dep
