### ISSUE TITLE
[Request dependency] directmusic dsound

### ISSUE THREAD

**Issue by ciandonovan** [bottlesdevs/dependencies#56]
**Dependency name**: directmusic dsound

**Official link to the download page (not direct download)** `$ winetricks directmusic dsound`

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
https://wiki.winehq.org/Sound#DirectMusic_support

**Comment by francescomasala** [comment]
Finding a redistributable package

I'll post updates

**Comment by francescomasala** [comment]
Found the redis. I'll make the .yml

**Comment by ciandonovan** [comment]
Sound! ;) Did you find both the directmusic and dsound redistributables? Microsoft don't make it easy to find through searching their website, but running winetricks should give URLs to both of them. I don't have winetricks installed at the moment unfortunately, but can spin it up in a container just to find the URL if needs be

**Comment by francescomasala** [comment]
I moved the installer into our [cdn](https://cdn.usebottles.com/dependencies/directx_feb2010_redist.exe
) and I'm trying to figure out if I need to include them since they're obsolete since vista (and in theory only 32 bit)

**Comment by francescomasala** [comment]
So, small problem, I need to test the dependency calmly and most likely integrate it along with issue #53

Sorry for the delay :P

**Comment by pm4rcin** [comment]
I have flatpak installation of bottles and a game that requires directmusic to have music working so I could help with testing.

**Comment by mirkobrombin** [comment]
Locked by https://github.com/bottlesdevs/Bottles/issues/1485

**Comment by pm4rcin** [comment]
@mirkobrombin there's a Github action for dependent issues. I think it could be worth adding it to the project: https://github.com/marketplace/actions/dependent-issues
