### ISSUE TITLE
[BUG] dotnet472 installation fails with 'already installed'

### ISSUE THREAD

**Issue by nill14** [bottlesdevs/dependencies#58]
This issue has been originally reported here:
https://github.com/bottlesdevs/dependencies/issues/47

**Describe the bug**
Installation of dotnet472 into a newly created application bottle fails. The setup program returns with blocked installation. It claims dotnet472 is installed but it isn't.

**Steps to reproduce:**
    create a new application bottle
    from dependencies tab select dotnet472
    dotnet installation fails (The installation was blocked)
    The installation is blocked because it says it is already installed. (It isn't.)
    Verify that dotnet472 is not installed (either by registry keys, or by an app requiring it)

**How to check that dotnet version is installed:**
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Wayland

**Comment by Talon1024** [comment]
I was able to get around this issue by setting the Windows version (Preferences -> System -> Windows Version) to Windows 7. When I did so, I had already tried and failed to install dotnet472 with the Windows version set to Windows 10. I guess the .NET 4.7.2 installer assumes it's already installed on Windows 10.

**Comment by pbuyle** [comment]
I had the same issue (also running in Flatpak). Using the Bottles UI to change the Windows version did nit work. When using the Wine Configuration utility, it was still set to Windows 10. Setting it to Widows 7 there allowed me to install .Net 4.7.2.
