### ISSUE TITLE
[Report] The font "Arial Unicode MS.ttf" for FireAlpaca

### ISSUE THREAD

**Issue by AlexBigCheese** [bottlesdevs/dependencies#59]
**Dependency name**: arial-unicode-ms

**Official link to the download page (not direct download)** No clue

**Is this dependency compatible with Wine?**
- [X] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
https://firealpaca.com/
https://www.reddit.com/r/linuxquestions/comments/q9t9bl/wine_cannot_display_certain_text_after_switching/hgyflpk/

The user said to fix the "bush hid the facts" rendering of layer names in FireAlpaca they had to install all fonts available in WineTricks.
FireAlpaca can open PSD files correctly (because of it's clipping mask support), GIMP and Krita do not work.
UPDATE: The font is called "Arial Unicode MS.ttf"

**Comment by AlexBigCheese** [comment]
Ok it's called "Arial Unicode MS.ttf", that's the font it needs, i put it in the windows/Fonts folder and the layer names now render!

**Comment by mirkobrombin** [comment]
Thanks for reporting. We will provide a dependency for it
