### ISSUE TITLE
[Request dependency] mfc42

### ISSUE THREAD

**Issue by Askaiant** [bottlesdevs/dependencies#69]
**Dependency name**: mfc42

**Official link to the download page (not direct download)** https://www.dll-files.com/mfc42.dll.html

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
[winetricks can't install mfc42](https://askubuntu.com/questions/169218/winetricks-cant-install-mfc42)

**Comment by tiziodcaio** [comment]
Try installing vcredist6sp4

**Comment by vickyorlo** [comment]
Can confirm that vcredist6sp4 provides mfc42.dll and mfc42u.dll.

**Comment by mirkobrombin** [comment]
I think we can close

**Comment by Arcitec** [comment]
Future visitors: I can also confirm that the newer "vcredist6sp6" does NOT contain "mfc42u.dll". You MUST install the older "vcredist6" (sp4) to get that file.
