### ISSUE TITLE
[Request dependency] cjkfonts

### ISSUE THREAD

**Issue by MagicalDrizzle** [bottlesdevs/dependencies#7]
**Dependency name**: cjkfonts

**Official link to the download page (not direct download)** https://www.ctan.org/pkg/cjk-fonts
**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
They can be links to guides for its implementation or testing or other. Each reference can be useful to maintainers to implement the dependency.

**Comment by mirkobrombin** [comment]
I think it is more complicated then expected. Winetricks provide fake fonts for ch/ja/ko, creating aliases using Source Han Sans fonts. I have no idea why, I have not found any references but I think it is due to compatibility issues and I will do it in the same way.

**Comment by mirkobrombin** [comment]
Blocked by https://github.com/orgs/bottlesdevs/projects/6#card-68421572

**Comment by mirkobrombin** [comment]
Implemented. As it need the new `replace_font` method, it will be available after 2021.9.14 will be released.
