### ISSUE TITLE
[Report] AdobeAIR.exe failed cksum / broken url

### ISSUE THREAD

**Issue by ServerMonkey** [bottlesdevs/dependencies#70]
**Which dependency?**
e.g. aairruntime

**Problem type**
- download failed/broken url
```
INFO Renaming [AdobeAIR.exe] to [adobeair.exe]. 
ERROR Downloaded file [AdobeAIR.exe] looks corrupted. 
ERROR Source cksum: [8d377b130be65e67a845c89e0117c305] downloaded: [d7c6a96daad7ce9718feb4aa4eaef4ac] 
INFO Removing corrupted file [AdobeAIR.exe].
```

**Describe the problem**
harman.com clearly updated their URL.
https://airsdk.harman.com/assets/downloads/AdobeAIR.exe points now to the latest release of Adobe AIR.

The version with the hash 8d377b130be65e67a845c89e0117c305 is now located here: https://airsdk.harman.com/assets/downloads/33.1.1.743/AdobeAIR.exe

**Comment by mirkobrombin** [comment]
Thanks for reporting
