### ISSUE TITLE
[Request dependency] d3dx11

### ISSUE THREAD

**Issue by ouvoun** [bottlesdevs/dependencies#72]
**Dependency name**:
d3dx11

**Official link to the download page (not direct download)**
https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Comment by tiziodcaio** [comment]
Why not using simply DXVK?

**Comment by mirkobrombin** [comment]
DXVK translates to vulkan

**Comment by mirkobrombin** [comment]
Already provided
