### ISSUE TITLE
[Report] msxl3 can not install properly

### ISSUE THREAD

**Issue by RushingAlien** [bottlesdevs/dependencies#83]
**Which dependency?**
msxml3

**Problem type**
Not properly installed, program has errors about msxml3. Doesn't happen when installed via winetrick

**Describe the problem**
before we install msxml3 we need to remove the one wine has builtin since the one wine has builtin has a higher version number.
```
load_msxml3()
{
    # Service Pack 7
    # Originally at https://download.microsoft.com/download/8/8/8/888f34b7-4f54-4f06-8dac-fa29b19f33dd/msxml3.msi
    # Mirror list: http://www.filewatcher.com/m/msxml3.msi.1070592-0.html
    # Known bad sites (2017/06/11):
    # ftp://support.danbit.dk/D/DVD-RW-USB2B/Driver/Installation/Data/Redist/msxml3.msi
    # ftp://94.79.56.169/common/Client/MSXML%204.0%20Service%20Pack%202/msxml3.msi
    w_download https://media.codeweavers.com/pub/other/msxml3.msi f9c678f8217e9d4f9647e8a1f6d89a7c26a57b9e9e00d39f7487493dd7b4e36c

    # It won't install on top of Wine's msxml3, which has a pretty high version number, so delete Wine's fake DLL
    rm "${W_SYSTEM32_DLLS}"/msxml3.dll
    w_override_dlls native msxml3
    w_try_cd "${W_CACHE}/${W_PACKAGE}"

    # See https://github.com/Winetricks/winetricks/issues/1086
    # and https://bugs.winehq.org/show_bug.cgi?id=26925
    if w_workaround_wine_bug 26925 "Forcing quiet install"; then
        w_try "${WINE}" msiexec /i msxml3.msi /q
    else
        w_try "${WINE}" msiexec /i msxml3.msi ${W_OPT_UNATTENDED:+/q}
    fi
}
```
winetrick's verb for reference

**Comment by mirkobrombin** [comment]
You are right, we need to use the `override_dll` action

**Comment by RushingAlien** [comment]
hm... the 32 bit dlls installation is still broken unless I manually remove /syswow64/msxml3.dll myself for some reason. 

Bottles version :  2022.5.2-trento-1\
Package Format : Flatpak
Distro : Arch Linux
WIndowing System : Wayland
DE : GNOME 42

I'm lost honestly.

**Comment by RushingAlien** [comment]
before

**Comment by mirkobrombin** [comment]
Mmh this is weird, the installer remove it as first step:
https://github.com/bottlesdevs/dependencies/blob/ebac16b5b885acf6b109ef6c6f668d8c93fe39e2/Essentials/msxml3.yml#L10

(win32 is a placeholder to system32/syswow64 according to your bottle architecture). I'll do another test asap

**Comment by RushingAlien** [comment]
To easily check, without hashes or sha256, if Microsoft's 32 bit msxml3.dll is installed is to simply see if 32 bit msxml3.dll is 1 MB as opposed to Wine's 2.8 MB of their implemention of msxml3.dll. And also, to see if msxml3r.dll is available in the 32 bit folder.

**Comment by mirkobrombin** [comment]
Fixed, it was my fault. Bottles was trying to remove msxml3 instead of msxml3.dll ahah

**Comment by RushingAlien** [comment]
I have confirmed that the installation is successful on my end. Thank you so much.
