### ISSUE TITLE
[Request dependency] dsdmo

### ISSUE THREAD

**Issue by Somaxa8** [bottlesdevs/dependencies#88]
**Dependency name**: dependency name here

**Official link to the download page (not direct download)** https://...

**Is this dependency compatible with Wine?**
- [X] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
winetricks dsdmo

https://github.com/Winetricks/winetricks/blob/master/src/winetricks

**Comment by mirkobrombin** [comment]
Publishing need 2022.5.28-2 with regsvr32 support
