### ISSUE TITLE
[Request dependency] galliumnine

### ISSUE THREAD

**Issue by Somaxa8** [bottlesdevs/dependencies#89]
**Dependency name**: dependency name here

**Official link to the download page (not direct download)** https://...

**Is this dependency compatible with Wine?**
- [X] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
winetricks galliumnine

https://github.com/Winetricks/winetricks/blob/master/src/winetricks

**Comment by francescomasala** [comment]
Moved to issue https://github.com/bottlesdevs/components/issues/131
