### ISSUE TITLE
[Request dependency] cmd

### ISSUE THREAD

**Issue by DeiDo** [bottlesdevs/dependencies#96]
**Dependency name**: cmd

**Official link to the download page (not direct download)**

**Is this dependency compatible with Wine?**
- [x] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
winetricks cmd

https://github.com/Winetricks/winetricks/blob/master/src/winetricks

Direct download:
https://web.archive.org/web/20150526022037/http://download.microsoft.com/download/8/d/c/8dc79965-dfbc-4b25-9546-e23bc4b791c6/Q811493_W2K_SP4_X86_EN.exe

**Comment by daynashaw** [comment]
This is required for the installation of STALKER GAMMA. Would y'all be amenable to re-opening this issue?

https://discord.com/channels/912320241713958912/976570969768476753/990704301280219146

**Comment by SnenxyTengoku** [comment]
+1, this is required for some applications to work properly.
